ARG SHOWCASE_VERSION=101
FROM curs/showcase:6.1.${SHOWCASE_VERSION}

# environment variables for generalapp.properties file
ENV showcase_web.console.size=100
ENV showcase_web.console.add.text.files=100
ENV showcase_id.casesensitive=false
ENV showcase_jmx.enable=false

ENV showcase_security.crossdomain.authentication=false
ENV showcase_login.title=Showcase
ENV showcase_copy.common.files.on.startup=true
ENV showcase_delete.solutions.dir.on.tomcat.startup=true
ENV showcase_celesta.skip.dbupdate=false
ENV showcase_celesta.force.dbinitialize=false

# create directory for userdata
RUN mkdir userdata
# set generalapp properties 
COPY ./properties.sh bin/properties.sh

ENTRYPOINT [ "properties.sh" ]

CMD [ "catalina.sh", "run" ]
